#!/bin/bash

example_projects_dir="example_projects"
project_dir="$example_projects_dir/test_project"
rm -rf $project_dir
cd $example_projects_dir
mix new test_project > /dev/null 2>&1
pwd
./../bp init --cwd test_project
init_result=$?
./../bp run --cwd test_project
run_result=$?
if [ $init_result -ne 0 ]; then
  echo "FAILED - mix build_pipeline.init"
  exit 1
fi

if [ $run_result -ne 0 ]; then
  echo "FAILED - mix build_pipeline.run"
  exit 1
fi
rm -rf $project_dir
exit 0
