#!/bin/bash

find_result=$(git grep TODO -- './*' ':!build' ':!.credo.exs')
result=$?
if [ $result -eq 0 ]; then
  echo "TODO found in:"
  echo "$find_result" | while read -r res; do echo " - $res"; done
  exit 1
fi
