#!/bin/bash

output=$(./bp_dev run --cwd example_projects/long_running_step_after_failure)
run_result=$?

if [ $run_result -ne 1 ]; then
  echo "./bp run --cwd example_projects/long_running_step_after_failure"
  echo "Should have failed, but it gave an exit code other than 1??"
  exit 1
fi

ps aux | grep "[s]leep_for_ages" 2>&1 /dev/null

if [[ $? -ne 0 ]]; then
  echo "Failed to shut down the build_step 'sleep_for_ages' which should happen automatically because a different build_step already failed".
  exit 1
fi

ps aux | grep "[s]leep 27" 2>&1 /dev/null

if [[ $? -ne 0 ]]; then
  echo "Failed to shut down the build_step 'sleep_for_ages' because it's command 'sleep 27' is still running".
  exit 1
fi
