on:
  pull_request:
  push:
    branches: [main]

jobs:
  lints:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      # Verify that we can build the escript from the flake.
      # This is primarily a test of the Mix dependencies hash being up-to-date
      # in the flake.
      - run: nix build .
